CREATE TABLE client (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DOCUMENT VARCHAR(100),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    PRIMARY KEY(ID)
);